<?php
//ye str ko binary sey hex mia convert_uudecode kr dey ga...hex2bin ye hex sey bin mia convert kr ddey ga...
//convert ascii char to hexdecimal values ascii values kia hian jo ap key board mia hain wo ascii hain...
//net sey table search kr lo is ka...mil jaye ga easily...
//jitna string bara ho ga wasiy hi code bhi...

$str=bin2hex("hello g i,am hanzla shahzad");

echo $str."<br>";

//hex2bin...

echo hex2bin($str);
 ?>
